baseURL: 'https://jo-minjun.github.io/'
languageCode: 'kr'
title: "minjun's note"
theme: 'hugo-PaperMod'

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: categories
      name: Categorie
      url: categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10

params:
  homeInfoParams:
    Title: 'test'
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: 'https://github.com/jo-minjun'

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
