baseURL: "https://jo-minjun.github.io"
languageCode: "kr"
title: "minjun's memory"
theme: "hugo-PaperMod"

menu:
  main:
    - identifier: search
      name:
      url: search
      weight: 1
      pre:
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="11" cy="11" r="8"></circle>
        <line x1="23" y1="23" x2="16.65" y2="16.65"></line>
        </svg>
    - identifier: categories
      name: Categories
      url: categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: tags/
      weight: 40
    - identifier: notes
      name: Notes
      url: notes/
      weight: 60
    - identifier: etc
      name: 끄적끄적
      url: etc/
      weight: 80

params:
  homeInfoParams:
    Title: "민준의 블로그"
    Content: |
      - 산업기능요원으로 근무하고 있는 2년차 백엔드 개발자 조민준입니다.

  socialIcons:
    - name: email
      url: "mailto:alswns9288@gmail.com"
    - name: github
      url: "https://github.com/jo-minjun"
    - name: linkedin
      url: "https://www.linkedin.com/in/minjun-jo-8007a0238"
    - name: instagram
      url: "https://instagram.com/j0_minjun?igshid=MjkzY2Y1YTY="

  comments: true

  # 사진 상세 보기
  cover:
    linkFullImages: true

  # 게시물 상단 현재 디렉토리
  ShowBreadCrumbs: true
  # 게시물 하단 네비게이션
  ShowPostNavLinks: true
  # 코드 copy 버튼
  ShowCodeCopyButtons: true

  # 검색 옵션
  # See https://fusejs.io/api/options.html
  fuseOpts:
    minMatchCharLength: 2
    distance: 1000
    threshold: 0.3
    keys:
      - title
      - permalink
      - summary
      - content

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

