baseURL: 'https://jo-minjun.github.io/'
languageCode: 'kr'
title: "minjun's memory"
theme: 'hugo-PaperMod'

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: categories
      name: Categorie
      url: categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10

params:
  homeInfoParams:
    Title: "memory repository"
    Content: 공부, 생각, 잡담 등 기억하고 싶은 내용을 저장합니다.

  socialIcons:
    - name: github
      url: 'https://github.com/jo-minjun'

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowPostNavLinks: true
