baseURL = "http://blog.minjun.pe"
title = "Hello Hugo"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
avatarURL = "images/avatar.jpg"

[params]
author = "jo-minjun"
description = "jo-minjun의 메모장"
keywords = "blog,developer,personal"
info = ["Backend Developer"]
dateFormat = "January 2, 2006"
since = 2022
colorScheme = "auto"
maxSeeAlsoItems = 5

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "null"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Post"
weight = 2
url = "posts/"
