# baseURL = "http://blog.minjun.note"
# title = "Hello Hugo"
# theme = "hugo-coder"
# languageCode = "kr"
# defaultContentLanguage = "kr"
# paginate = 20
# pygmentsStyle = "bw"
# pygmentsCodeFences = true
# pygmentsCodeFencesGuessSyntax = true
# enableEmoji = true
# avatarURL = "images/avatar.jpg"

# [params]
# author = "jo-minjun"
# description = "jo-minjun의 메모장"
# keywords = "blog,developer,personal"
# info = ["Backend Developer"]
# dateFormat = "January 2, 2006"
# since = 2022
# colorScheme = "auto"
# maxSeeAlsoItems = 5

# [[params.social]]
# name = "Github"
# icon = "fa fa-2x fa-github"
# weight = 1
# url = "null"

# [[languages.kr.menu.main]]
# name = "About"
# weight = 1
# url = "about/"

# [[languages.kr.menu.main]]
# name = "Note2"
# weight = 2
# url = "/note/infra_version-control"

# [[languages.kr.menu.main]]
# name = "Note"
# weight = 2
# url = "/note"

baseURL: 'http://blog.minjun.note'
languageCode: 'kr'
title: "minjun's note"
theme: 'hugo-PaperMod'

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categorie
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10

params:
  homeInfoParams:
    Title: 'test'
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: 'https://github.com/jo-minjun'

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
