name: github pages

on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

        # with:
        #   token: ${{ secrets.GIT_TOKEN }}
        #   submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: site-verification
        run: echo "${{ secrets.SITE_VERIFICATION }}" > ./public/google34bf590cfe76298c.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          persional_token: ${{ secrets.GIT_TOKEN }}
          external_repository: jo-minjun/jo-minjun.github.io
          user_name: jo-minjun
          user_email: alswns9288@gmail.com
          publish_branch: main
          publish_dir: ./public
